### ISSUE TITLE
SBGN: DNA-ATP complex should necessarily-stimulate replication

### ISSUE THREAD

**Issue by binfalse** [dagwa/wholecell-replication#13]
You modeled the start of replication as a catalysis, but from how we understand the process that should be a necessary stimulation instead. We suggest using the `---|->` instead of `----o`

**Comment by KniSche** [comment]
The current symbol is "modulation" (SBGN User manual; section 2.4.3) . The "necessary stimulation" (2.4.7) should indeed be used instead as it explicitly defines the DNAa-ATP as necessary for the process to take place. Cheers for this - I'll edit the file now.

**Comment by KniSche** [comment]
Can somebody check to see if the new file works with SBGN (I edited the file in text)? I cannot get the .sbgn files to open in vanted.
-------- EDIT --------
Was missing SBGN-ED addon. File opens fine and the correct arc is now displayed.

**Comment by jannisuhlendorf** [comment]
I had a quick look and the SBGN opens in vanted (you need to install the
SBGN extension for vanted). I did not check whether the content is
correct though.

cheers,
Jannis

Am 27.03.2015 um 13:56 schrieb Vincent Knight-Schrijver:

> Can somebody check to see if the new file works with SBGN (I edited
> the file in text)? I cannot get the .sbgn files to open in vanted.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dagwa/wholecell-replication/issues/13#issuecomment-86932900.

## 

Dr. Jannis Uhlendorf
Humboldt University Berlin
Institute for Biology
Theoretical Biophysics
Invalidenstr. 42, 10115 Berlin, Germany

Phone: +49 30 2093 8389
Email: jannis.uhlendorf@hu-berlin.de

**Comment by jhsong111** [comment]
Hello, 
I just checked with VANTED and found that the modification is correct according to the SBGN User Manual  2.4.7. 
Best, 
Je-Hoon Song
